### ISSUE TITLE
Consider run some (optional) checks before uploading

### ISSUE THREAD

**Issue by jneira** [haskell-actions/hackage-publish#6]
Hi! many thanks for this action, that can make easier the development of projects with many packages like haskell-language-server

have you considered run optionally some sanity checks before uploading it, for example `cabal check` and `cabal haddock` (as the upload can fail due to haddock errors afaik)?

**Comment by AlexeyRaga** [comment]
I was thinking about that, but haven't included it into an action for the following reasons:

1. It can be done separately very simply.
2. This action deliberately doesn't require and doesn't use `cabal`. It takes packages (and docs) tarballs that have already been pre-built.
3. In different scenarios you may want different checks and at different times. For example, you may want to call `cabal check` at the very beginning of your build to fail faster and to avoid wasting CI/iteration time in cases when checks don't pass. 

> as the upload can fail due to haddock errors afaik

No, because this action will either find a tarball or it won't. Building tarballs is a part of your build step.
But since it it doesn't build tarballs it won't fail on haddock errors.

Something like:

```yaml
      - name: Configure
        run: |
          cabal update
          cabal configure --enable-documentation --enable-tests --write-ghc-environment-files=ghc8.4.4+

      - name: Build
        run: cabal build all

      - name: Create package
        run: |
          cabal haddock all      # this may be redundant because `--enable-documentation` above forces it
          cabal sdist all
```
